name: Build and Push Docker Image

# Trigger the workflow on push to the master branch or on pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # The GitHub Actions runner will run on Ubuntu

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using secrets for authentication
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image and tag it with the GitHub repository name and branch
      - name: Build Docker image
        run: |
          IMAGE_TAG="rax123/my-python-app:${{ github.sha }}"  # Tag with commit SHA
          docker build -t $IMAGE_TAG .
          
      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_TAG="rax123/my-python-app:${{ github.sha }}"  # Ensure consistent tagging
          docker push $IMAGE_TAG
